#!/bin/bash
#
# Title:      Football file webserver
# Author(s):  timekills
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'football'
        intport: '80'
        extport: '7979'
        image: 'plehr/docker-php-sqlsrv-curl'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

#   - name: 'Including plugins'
#      include_tasks: '/opt/communityapps/apps/_plugins.yml'

#    - name: 'Including folders'
#      include_tasks: '/opt/communityapps/apps/_downloaders.yml'

    - name: 'Ini Check'
      stat:
        path: /opt/appdata/{{pgrole}}/core.conf
      register: inicheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/mnt/unionfs/Football:/var/www/html'
          - '/mnt:/mnt'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting default ENV'
      set_fact:
        pg_env:
          USER_ID: 1000
          GROUP_ID: 1000

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
