#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "rutorrent-pyrocore"
      intport: "80"
      extport: "5898"
      intport2: "51415"
      extport2: "51415"
      intport3: "3000"
      extport3: "3000"
      image: "romancin/rutorrent-flood:latest"

# CORE (MANDATORY) ############################################################
  - name: CronJob Role
    include_tasks: "/opt/plexguide/containers/_core.yml"
    
  - name: 'Including plugins'
    include_tasks: '/opt/communityapps/apps/_plugins.yml'
  
  - name: 'Including folders'
    include_tasks: '/opt/communityapps/apps/_downloaders.yml'
        
  - name: 'Ini Check'
    stat:
      path: /opt/appdata/{{pgrole}}/core.conf
    register: inicheck

# LABELS ######################################################################

  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.enable: "true"
        traefik.port: "{{intport}}"
        traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - "/opt/appdata/{{pgrole}}:/config"
        - '{{path.stdout}}:{{path.stdout}}'
        - '/mnt:/mnt'
        - '/mnt/unionfs:/unionfs'
        - '/mnt/downloads/{{pgrole}}:/downloads/complete'
        - '/mnt/incomplete/{{pgrole}}:/downloads/incomplete'
        - "/etc/localtime:/etc/localtime:ro"

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000

# MAIN DEPLOYMENT #############################################################

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "{{pgrole}}"
      image: "{{image}}"
      pull: yes
      published_ports:
        - '{{ports.stdout}}{{extport}}:{{intport}}'
        - '{{ports.stdout}}{{extport2}}:{{intport2}}'
        - '{{extport3}}:{{intport3}}'
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: always
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      labels: "{{pg_labels}}"
